### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by Faith-Code** [TUI-NICR/ESANet#1]
First thank you for sharing the excellent work for us. I cannot open the links to download pretrained models, can you send them all to my email? Thank you very much, the email is cqin_hbsz@163.com.

**Comment by mona0809** [comment]
We just double-checked, but the links seem fine from here. Can you explain your problem with the links in more detail? Unfortunately, the weights are too large for sending via mail.

**Comment by Faith-Code** [comment]
OK, I got it, thank you.
