### ISSUE TITLE
ESANet-R18-NBt1D pretrained weights

### ISSUE THREAD

**Issue by suyuzhang** [TUI-NICR/ESANet#22]
Hi @danielS91, 
Thanks for your work!
Could you provide ESANet-**R18**-NBt1D pretrained weights on ImageNet?

**Comment by danielS91** [comment]
You will find the model [here](https://drive.google.com/file/d/1tcluAbGUqzXut2sWsUDm7WX2jkSMwT85/view?usp=sharing).

**Comment by suyuzhang** [comment]
@danielS91 Thanks!
