### ISSUE TITLE
The fps cannot reach 29.7 on agx by tensorrt

### ISSUE THREAD

**Issue by hlyf-xs** [TUI-NICR/ESANet#32]
This's a great project, It shows only 15.16 fps  which I run the ESANet-R34-NBt1D model on the jetson AGX by tensorrt. I confused where wrong

**Comment by danielS91** [comment]
There is something wrong - it is way too slow.

Which version of Jepack, TensorRT and PyTorch are you using? However, without sharing the command-line call including all passed parameters, it is not possible to identify any reason.

**Comment by hlyf-xs** [comment]
Sorry for the late reply, It shows only 15.16 fps when I use the environment which Jepack4.5,TensorRT 7.1.3, cuda10.2 and Pytorch 1.17.0, and the command-line is "python inferrence_time_whole_model.py --dataset nyuv2 --no_time_pytorch --no_time_onnxruntime --trt_floatx 16"



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Daniel ***@***.***&gt;; 
发送时间: 2021年12月10日(星期五) 下午4:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TUI-NICR/ESANet] The fps cannot reach 29.7 on agx by tensorrt (Issue #32)





 
There is something wrong - it is way too slow.
 
Which version of Jepack, TensorRT and PyTorch are you using? However, without sharing the command-line call including all passed parameters, it is not possible to identify any reason.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hlyf-xs** [comment]
> Sorry for the late reply, It shows only 15.16 fps when I use the environment which Jepack4.5,TensorRT 7.1.3, cuda10.2 and Pytorch 1.17.0, and the command-line is "python inferrence_time_whole_model.py --dataset nyuv2 --no_time_pytorch --no_time_onnxruntime --trt_floatx 16"
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Daniel ***@***.***&gt;; 发送时间: 2021年12月10日(星期五) 下午4:12 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [TUI-NICR/ESANet] The fps cannot reach 29.7 on agx by tensorrt (Issue #32) There is something wrong - it is way too slow. Which version of Jepack, TensorRT and PyTorch are you using? However, without sharing the command-line call including all passed parameters, it is not possible to identify any reason. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.



> Sorry for the late reply, It shows only 15.16 fps when I use the environment which Jepack4.5,TensorRT 7.1.3, cuda10.2 and Pytorch 1.17.0, and the command-line is "python inferrence_time_whole_model.py --dataset nyuv2 --no_time_pytorch --no_time_onnxruntime --trt_floatx 16"
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Daniel ***@***.***&gt;; 发送时间: 2021年12月10日(星期五) 下午4:12 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [TUI-NICR/ESANet] The fps cannot reach 29.7 on agx by tensorrt (Issue #32) There is something wrong - it is way too slow. Which version of Jepack, TensorRT and PyTorch are you using? However, without sharing the command-line call including all passed parameters, it is not possible to identify any reason. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hlyf-xs** [comment]
> There is something wrong - it is way too slow.
> 
> Which version of Jetpack, TensorRT, and PyTorch are you using? However, without sharing the command-line call including all passed parameters, it is not possible to identify any reason.

how can I identify the reason?
