### ISSUE TITLE
how to solve the below question?

### ISSUE THREAD

**Issue by zhouqunbing** [TUI-NICR/ESANet#37]
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by mona0809** [comment]
Where does this error occur? Please provide the full call and error log.

**Comment by mona0809** [comment]
Sorry, I can not reproduce the error. It seems like you can not download the NYUv2 data: 
https://github.com/TUI-NICR/ESANet/blob/e929e47feaba7aa6d612648f610d9fe55ce375d1/src/datasets/nyuv2/prepare_dataset.py#L32
Can you manually download the mat file?

**Comment by zhouqunbing** [comment]
> > 
> 
> > Sorry, I can not reproduce the error. It seems like you can not download the NYUv2 data:
> > https://github.com/TUI-NICR/ESANet/blob/e929e47feaba7aa6d612648f610d9fe55ce375d1/src/datasets/nyuv2/prepare_dataset.py#L32
> 
> > Can you manually download the mat file?
> > yes,i download the dataset manually, it is ''nyu_depth_v2_labeled.mat'',but i do
> > not know how to unzip or convert the ''nyu_depth_v2_labeled.mat'',which file do i need to run?Thank you very much.

i have solved the bug, my cuda memory is to small to unzip,thank you very much,respect to you.
