### ISSUE TITLE
RGB inference only

### ISSUE THREAD

**Issue by tamnguyenvan** [TUI-NICR/ESANet#4]
Dear team,
Thank you for this awesome project. My question is can I run segmentation inference with RGB input images only?

**Comment by mona0809** [comment]
The model trained on both RGB and depth expects both inputs as well. I just tried to replace the depth image with a dummy image consisting of the mean depth values but the result is not very accurate. I encourage you to train the model on RGB images only with the argument `--modality rgb`.

**Comment by tamnguyenvan** [comment]
Thank you @mona0809 for quick reply. I will give it a try and let you know the result.

**Comment by tamnguyenvan** [comment]
Hi @mona0809 , I've been trying to train the model with RGB image only. But I can't found encoder pretrained weightson ImageNet. If it's possible, can you please share the weights file? ImageNet is huge. I don't have that much resource to train it from scratch.
Many thanks.

**Comment by danielS91** [comment]
Our readme file already contains a link to the pretrained weights, see [training section](https://github.com/TUI-NICR/ESANet#training)

**Comment by tamnguyenvan** [comment]
You're awesome. Thank you @danielS91

**Comment by tamnguyenvan** [comment]
Hi team,
I've trained NYUv2 on RGB images only (with `--modality rgb` as @mona0809 mentioned) but I've just got ~41 mIOU. How can I reach ~50 mIOU or it's just limitation of rgb only model? I just want to train only one class (floor). Do you think it would be better if it was trained on 1 class instead?
My `argsv.txt`:
```
train.py --dataset nyuv2 --dataset_dir ./src/datasets/nyuv2 --pretrained_dir ./trained_models/imagenet --results_dir ./results --batch_size 4 --modality rgb
```
My `args.json`:
```
{
    "activation": "relu",
    "aug_scale_max": 1.4,
    "aug_scale_min": 1.0,
    "batch_size": 4,
    "batch_size_valid": null,
    "c_for_logarithmic_weighting": 1.02,
    "channels_decoder": 128,
    "class_weighting": "median_frequency",
    "context_module": "ppm",
    "dataset": "nyuv2",
    "dataset_dir": "./src/datasets/nyuv2",
    "debug": false,
    "decoder_channels_mode": "decreasing",
    "encoder": "resnet34",
    "encoder_block": "NonBottleneck1D",
    "encoder_decoder_fusion": "add",
    "encoder_depth": null,
    "epochs": 500,
    "finetune": null,
    "freeze": 0,
    "fuse_depth_in_rgb_encoder": "SE-add",
    "he_init": false,
    "height": 480,
    "last_ckpt": "",
    "lr": 0.005,
    "modality": "rgb",
    "momentum": 0.9,
    "nr_decoder_blocks": [
        3
    ],
    "optimizer": "SGD",
    "pretrained_dir": "./trained_models/imagenet",
    "pretrained_on_imagenet": true,
    "pretrained_scenenet": "",
    "raw_depth": false,
    "results_dir": "./results",
    "upsampling": "learned-3x3-zeropad",
    "valid_full_res": false,
    "weight_decay": 0.0001,
    "width": 640,
    "workers": 8
}
```

**Comment by mona0809** [comment]
RGB only definitely leads to worse results. The architecture is developed for incorporating depth information in a strong and efficient way. There might be architectures, which are better suited for RGB only. According to our paper the RGB only version with ResNet 34 encoder with NonBottleneck1D block (ResNet34 NBt1D) reaches around 43 mIoU (see Fig. 3). The lower batch size of 4 might account for your lower mIoU. Training on the larger SUN RGB-D dataset might also help - not for a higher mIoU but possibly for the downstream application.

You could try to train on the floor class only. However, this leads to a lot of void pixels and the number of floor pixels varies strongly in each batch, especially if the batch size is just 4. 

Let us know about your results 😉
