### ISSUE TITLE
logs.csv doesn't exist

### ISSUE THREAD

**Issue by sangwonme** [TUI-NICR/ESANet#40]
I'm having trouble with training ESA.

Pretrained weights link(https://drive.google.com/uc?id=1neUb6SJ87dIY1VvrSGxurVBQlH8Pd_Bi) provided here only has r34_NBt1D.pth file not the logs.csv file. So when I run the train.py, it shows like below.

`FileNotFoundError: [Errno 2] No such file or directory: './trained_models/imagenet/logs.csv'
`
Where can I get logs.csv file?
Is there any possible way except for running imagenet_pretraining.py by myself?

**Comment by mona0809** [comment]
What do you need the logs for? Can you please provide the full call and error log?

**Comment by mona0809** [comment]
Did you forgot to save the weights in the proper directory? By default the weights should be saved here: `./trained_models/imagenet/r34_NBt1D.pth`, as you can see in the code: https://github.com/TUI-NICR/ESANet/blob/a271ac55ca9d0801fd32c557789f2b908b8d9651/src/models/resnet.py#L473
Only if these weights are not found, the function tries to load the logs.

**Comment by sangwonme** [comment]
Oh thanks!
It was problem caused by wrong directory.
Now I can run train code!

Thanks a lot :)
