### ISSUE TITLE
A question about the unit of depth value(m or mm)

### ISSUE THREAD

**Issue by amokame** [TUI-NICR/ESANet#44]
Thanks a lot for your work!

I have a question about the unit of depth value, should it be meters or milimeters?
In nyuv2 files, it seems you change the unit to milimeters, but I didnot find similar process in Cityscapes data.

**Comment by danielS91** [comment]
It depends on the dataset: For all indoor datasets except of SUNRGB-D, we use mm as our data during application is in mm as well. For Cityscapes, we use m as the outdoor distances are much larger - mm would not fit an uint16 png.
However, during preprocessing, we apply a standardization with mean and std computed on the current input dataset anyway.

You have a look in our follow up work [EMSANet](https://github.com/TUI-NICR/EMSANet) and the related [dataset package](https://github.com/TUI-NICR/nicr-scene-analysis-datasets) - here we use hardcoded depth stats for standardization.

**Comment by amokame** [comment]
Thanks for your replying.
So the choice of the mm or m is dependent on the distance range of the particular dataset, got it.
