### ISSUE TITLE
Pretrained weight for Cityscapes (RGB-only)

### ISSUE THREAD

**Issue by matteosodano** [TUI-NICR/ESANet#53]
Hi,
thanks for the great work!
In the paper, you mention you trained a single-modality RGB version of ESANet on Cityscapes. Do you happen to still have the weights, by any chance?
Also, was it still the ResNet34+NBt1D trained with the same procedure you specify? 

Thanks again!

**Comment by danielS91** [comment]
Unfortunately, we do not have the weights of this run anymore. However, you can follow the instructions given here for Cityscapes: 
https://github.com/TUI-NICR/ESANet#training

Just change "--modality rgbd" to "--modality rgb". The remaining hyperparameter must be similar.

**Comment by matteosodano** [comment]
Ok, thanks!
